version: '3.1'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "65432:5432"
    volumes:
      - cameramenus_db:/var/lib/postgresql/data

  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    command: rails s -p 3000 -b 0.0.0.0
    environment:
      RAILS_PORT: 3000
      DATABASE_HOST: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      RAILS_ENV: development
      TMPDIR: /tmp
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - cameramenus_gems:/usr/local/bundle
      - ../.:/app
      - ./rails/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
  # nginx:
  #   image: nginx
  #   ports:
  #    - "80:80"
  #   environment:
  #    - NGINX_HOST=cameramenus1.com
  #    - NGINX_PORT=80
  #    - NGINX_PROXY=http://cameramenus:3000
  #   volumes:
  #     - .data/nginx/cameramenus_dev.template:/etc/nginx/conf.d/cameramenus_dev.template
  #     - ./cameramenus/public:/rails_public
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/cameramenus_dev.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  cameramenus_gems:
  cameramenus_db:
